[project]
name = "yolo-basket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bullmq>=2.13.1",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "redis>=5.2.1",
    "torch>=2.6.0",
    "ultralytics>=8.3.23",
]
